-- Campus Cafeteria PostgreSQL schema
CREATE TABLE IF NOT EXISTS roles (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id INTEGER NOT NULL REFERENCES roles(role_id),
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  is_active CHAR(1) NOT NULL DEFAULT 'Y' CHECK (is_active IN ('Y','N')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS menu_dates (
  menu_date_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_date DATE NOT NULL UNIQUE,
  is_published CHAR(1) NOT NULL DEFAULT 'Y' CHECK (is_published IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS menu_items (
  menu_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_date_id INTEGER NOT NULL REFERENCES menu_dates(menu_date_id),
  item_name VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  price NUMERIC(8,2) NOT NULL CHECK (price > 0),
  is_available CHAR(1) NOT NULL DEFAULT 'Y' CHECK (is_available IN ('Y','N'))
);

CREATE TABLE IF NOT EXISTS ingredients (
  ingredient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS item_ingredients (
  menu_item_id INTEGER NOT NULL REFERENCES menu_items(menu_item_id) ON DELETE CASCADE,
  ingredient_id INTEGER NOT NULL REFERENCES ingredients(ingredient_id),
  PRIMARY KEY (menu_item_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS stock (
  menu_item_id INTEGER PRIMARY KEY REFERENCES menu_items(menu_item_id) ON DELETE CASCADE,
  available_qty INTEGER NOT NULL DEFAULT 0 CHECK (available_qty >= 0)
);

CREATE TABLE IF NOT EXISTS pickup_windows (
  pickup_window_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  capacity INTEGER NOT NULL CHECK (capacity > 0),
  reserved_count INTEGER NOT NULL DEFAULT 0 CHECK (reserved_count >= 0),
  CHECK (end_time > start_time)
);

CREATE TABLE IF NOT EXISTS orders (
  order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id),
  pickup_window_id INTEGER NOT NULL REFERENCES pickup_windows(pickup_window_id),
  pickup_code VARCHAR(20) NOT NULL UNIQUE,
  order_status VARCHAR(20) NOT NULL DEFAULT 'PLACED'
    CHECK (order_status IN ('PLACED','PREPARING','READY','COLLECTED','CANCELLED')),
  total_amount NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
  ordered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cancelled_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_lines (
  order_id INTEGER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  menu_item_id INTEGER NOT NULL REFERENCES menu_items(menu_item_id),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(8,2) NOT NULL CHECK (unit_price > 0),
  PRIMARY KEY (order_id, menu_item_id)
);

CREATE TABLE IF NOT EXISTS order_status_history (
  history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  old_status VARCHAR(20),
  new_status VARCHAR(20) NOT NULL,
  changed_by INTEGER REFERENCES users(user_id),
  changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_menu_items_date ON menu_items(menu_date_id);
CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(order_status);
CREATE INDEX IF NOT EXISTS idx_orders_pickup ON orders(pickup_window_id);
CREATE INDEX IF NOT EXISTS idx_history_order ON order_status_history(order_id);
CREATE INDEX IF NOT EXISTS idx_pickup_windows_date ON pickup_windows(window_date);

-- Database-side trigger replaces the Oracle status trigger.
CREATE OR REPLACE FUNCTION record_order_status_change()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO order_status_history(order_id, old_status, new_status, changed_by)
    VALUES (NEW.order_id, NULL, NEW.order_status, NEW.user_id);
  ELSIF NEW.order_status IS DISTINCT FROM OLD.order_status THEN
    INSERT INTO order_status_history(order_id, old_status, new_status, changed_by)
    VALUES (
      NEW.order_id,
      OLD.order_status,
      NEW.order_status,
      NULLIF(current_setting('app.changed_by', true), '')::integer
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_order_status_history ON orders;
CREATE TRIGGER trg_order_status_history
AFTER INSERT OR UPDATE OF order_status ON orders
FOR EACH ROW EXECUTE FUNCTION record_order_status_change();
